name: Terraform CI/CD

on:
  push:
    branches:
      - master
      - feature/*  

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0  

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        id: plan
        run: terraform plan -out=tfplan

      - name: Upload Plan Artifact
        if: github.ref == 'refs/heads/master'
        uses: actions/upload-artifact@v2
        with:
          name: tfplan
          path: tfplan

      - name: Approval Step
        if: github.ref == 'refs/heads/master'
        run: |
          echo "Waiting for approval..."
          # You can implement a manual approval process here, e.g., using a GitHub Action for approval

      - name: Terraform Apply
        if: github.ref == 'refs/heads/master' && github.event_name == 'workflow_dispatch'
        run: terraform apply tfplan